### ISSUE TITLE
Does not "see" html tables 

### ISSUE THREAD

**Issue by nehri97** [martin-majlis/Wikipedia-API#11]
The page's text does not include the html tables when `ExtractFormat` is set to HTML
For instance, the filmography tables for actors and actresses does not appear in the page's text, even though they are html elements that should in principle be something we can see

**Comment by lmmx** [comment]
This goes for infobox tables too, unfortunately.

**Comment by martin-majlis** [comment]
I think that this issue is related to #6 

If you figure out which API call is returning information that you want in the form you want, please, reopen this ticket.
