### ISSUE TITLE
Categories are not being fetched for a category page

### ISSUE THREAD

**Issue by alexhunsley** [martin-majlis/Wikipedia-API#15]
This code prints no categories for the page in question (but it does contains categories):

```
import wikipediaapi

wiki_wiki = wikipediaapi.Wikipedia('en')

distsPage = wiki_wiki.page("Category:Continuous Distributions")
print("Category members: %s" % distsPage.title)

print(distsPage.categorymembers)

```

The output is:

```
Category members: Category:Continuous Distributions
{}
```

**Comment by martin-majlis** [comment]
@alexhunsley - this is really strange. It looks that this API somehow stopped working on Wikimedia side.

Underlying [API](https://www.mediawiki.org/w/api.php?action=help&modules=query%2Bcategorymembers) is also returning [nothing](https://www.mediawiki.org/w/api.php?action=query&list=categorymembers&cmtitle=Category:Continuous_Distributions). Even their example is returning [nothing](https://www.mediawiki.org/w/api.php?action=query&list=categorymembers&cmtitle=Category:Physics)

But it is interesting that API call [categoryinfo](https://en.wikipedia.org/w/api.php?action=query&prop=categoryinfo&titles=Category:Continuous_distributions)  - know that there are 171 pages and 3 subcategories.

You can try figure out which [API](https://en.wikipedia.org/w/api.php?action=help&modules=query) is returning what you want.

**Comment by martin-majlis** [comment]
If you will figure out how to extract that information, please, reopen this ticket.

**Comment by martin-majlis** [comment]
The issue is that that page does not exists.
* [https://en.wikipedia.org/w/api.php?action=query&list=categorymembers&cmtitle=Category:Continuous_distributions](Category:Continuous_distributions) - exists
* [https://en.wikipedia.org/w/api.php?action=query&list=categorymembers&cmtitle=Category:Continuous_Distributions](Category:Continuous_**D**istributions) - does not exist

```

import logging
import wikipediaapi

logging.basicConfig(level=logging.INFO)
wiki_wiki = wikipediaapi.Wikipedia('en')

pD = wiki_wiki.page("Category:Continuous Distributions")
print(pD.exists())
print(pD.categorymembers)

pd = wiki_wiki.page("Category:Continuous distributions")
print(pd.exists())
print(pd.categorymembers)

```
