### ISSUE TITLE
Hidden categories

### ISSUE THREAD

**Issue by twelveth** [martin-majlis/Wikipedia-API#16]
`categories` property despite 'normal' also gets [hidden categorires](https://en.wikipedia.org/wiki/Wikipedia:Categorization#Hiding_categories), which may be not so informative. I suppose, it is better to remove hidden cats with [`clshow`](https://www.mediawiki.org/wiki/API:Categories) or to make it not property, but method, which takes some flag as input, indicating whether to include hidden cats or not.

**Comment by martin-majlis** [comment]
Example:
* [Category:Deaf articles needing expert attention](https://en.wikipedia.org/wiki/Category:Deaf_articles_needing_expert_attention) - this is hidden category
* [Indo-Pakistani Sign Language](https://en.wikipedia.org/wiki/Indo-Pakistani_Sign_Language) - is page that has this category
* [API with more details](https://en.wikipedia.org/w/api.php?action=query&generator=categories&titles=Indo-Pakistani%20Sign%20Language&prop=info) - is not returning information whether it is or is not hidden category
* [Info about category](https://en.wikipedia.org/w/api.php?action=query&prop=info&titles=Category:Deaf%20articles%20needing%20expert%20attention) is also not returning information if it is hidden category or not

So it looks that API has to be changed.

**Comment by martin-majlis** [comment]
This functionality is now availble in version 0.5.0

```python
import wikipediaapi
wiki = wikipediaapi.Wikipedia('en')
page = wiki.page('Indo-Pakistani_Sign_Language')
wiki.categories(page)
len(wiki.categories(page)
# 19
len(wiki.categories(page, clshow='!hidden'))
# 5
```

Please, let me know if you have some other suggestions.
