### ISSUE TITLE
Connection doesn't support proxy

### ISSUE THREAD

**Issue by jinywu** [martin-majlis/Wikipedia-API#17]
I set environment variable HTTPS_PROXY, but it doesn't work.
So I pass proxies = {'https' : 'proxy.example.com:8080'} to requests.get, the it works.

**Comment by martin-majlis** [comment]
@jinywu : Support for proxy is part of the release 0.4.2. 

You can specify it in [constructor](https://wikipedia-api.readthedocs.io/en/latest/wikipediaapi/api.html#wikipediaapi.Wikipedia.__init__) while creating `Wikipedia` object.

```
Wikipedia('en', proxies={'http': 'http://localhost:1234'})
```
