### ISSUE TITLE
In Spanish Wikipedia: 104 is not a valid Namespace

### ISSUE THREAD

**Issue by fjhheras** [martin-majlis/Wikipedia-API#24]
I sometimes see the following error:

`ValueError: 104 is not a valid Namespace`

It seems that namespace 104 is not used in the 'en' Wikipedia, but it is used in other languages (for example, it is an annex to an article in 'es' wikipedia). The same is true for 102.

Adding entries in "wikipediaapi/__init__.py" (line 85) solves this error, but maybe there is a more general solution?

**Comment by GuillaumeDrillaud** [comment]
It's the same for French with 102 and 104 which are not valid namespace.

**Comment by martin-majlis** [comment]
Fixed in #25 - thanks for fixing this.
