### ISSUE TITLE
Feature - Http connection persistent

### ISSUE THREAD

**Issue by sidgitind** [martin-majlis/Wikipedia-API#26]
Is there a way to use http connection persistent feature in this library? That could make checking wikipedia faster. Thanks for the wonderful wrapper.

**Comment by martin-majlis** [comment]
Thanks @sidgitind for great idea how to improve performance of this library.

Based on my simple benchmark it reduce time to dowload 50 pages from 13s to 8s on my machine - https://github.com/martin-majlis/Wikipedia-API/commit/e16f5c4471581ed5f94dd85603a1201cddbbcf45

This feature is now available in version 0.5.3.
