### ISSUE TITLE
110 is not a valid Namespace

### ISSUE THREAD

**Issue by zoltan-fedor** [martin-majlis/Wikipedia-API#29]
In the Romanian Wikipedia I see the following sometimes:
`110 is not a valid Namespace`

While in the Russian one I see:
`106 is not a valid Namespace`

I assume this is a similar problem to https://github.com/martin-majlis/Wikipedia-API/issues/24

Could these be added to the Namespace class in https://github.com/martin-majlis/Wikipedia-API/blob/master/wikipediaapi/__init__.py?

**Comment by martin-majlis** [comment]
@zoltan-fedor : Do you have some example of page that has namespace 110, so I can add this into the tests?

**Comment by martin-majlis** [comment]
When will be Wikipedia available again - I will check those changes and release newer version. :)

Twitter: https://twitter.com/Wikipedia/status/1221513346781982722
Failed build: https://travis-ci.org/martin-majlis/Wikipedia-API/builds/642123009

**Comment by zoltan-fedor** [comment]
@martin-majlis, sorry, I don't have the exact page anymore, I only know that it was on some of the Russian language pages.

**Comment by martin-majlis** [comment]
This was fixed in release 0.5.4, where any integer is allowed - https://github.com/martin-majlis/Wikipedia-API/commit/1b677a27cf7e30ac24fb39cc863aa1e66005e558

Hopefully it will help you. :)

**Comment by zoltan-fedor** [comment]
Thanks!
