### ISSUE TITLE
How could I get Wiki infobox ?

### ISSUE THREAD

**Issue by wangkailut** [martin-majlis/Wikipedia-API#32]

**Comment by moscovig** [comment]
We do it manually (extra raw request). something like
`  title = title.replace(" ", "_")
    wiki_raw_url = "http://%s.wikipedia.org/w/index.php?title=%s" % (lang, title)
    response = _send_request(wiki_raw_url)
    soup = BeautifulSoup(response.content, "lxml")
    infobox = soup.find("table", class_="infobox")
    if infobox:
        for tr in soup.findAll("tr"):
            infobox_line = tr.text.replace("\n", "")
`
