### ISSUE TITLE
How do I avoid getting links that are not related to the page content?

### ISSUE THREAD

**Issue by tomersmadja** [martin-majlis/Wikipedia-API#34]
Hi,
I was wondering if I'm able to get only links that are in the page content.
For example, while I get the page about "Joseph Black" I get **108 links** mapped in a dictionary, among those links I find links to pages like [*doi*](https://en.wikipedia.org/wiki/Digital_object_identifier) which is not exactly related to the content of the page but to the references section.
How do I avoid this situation? Using the same example, how do I get for "Joseph Black" page, only the links between the beginning of the content to "See also" section (included).
I hope there is an easy way to do it.
Thanks

**Comment by martin-majlis** [comment]
When I check the [documentation](https://wikipedia-api.readthedocs.io/en/latest/wikipediaapi/api.html#wikipediaapi.Wikipedia.links) and pointers to the Wikipedia API that it contains it does not look that it would be possible. :/

Only extracting from the raw text itself - so iterate [over sections](https://wikipedia-api.readthedocs.io/en/latest/wikipediaapi/api.html#wikipediaapi.WikipediaPage.sections) and from the text extract links. This could be doable. :)

**Comment by martin-majlis** [comment]
These is another API call - [extracts](https://www.mediawiki.org/wiki/Extension:TextExtracts#API) - but it is not returning any HTML/Wiki tags to detect which words are links - https://en.wikipedia.org/w/api.php?action=query&prop=extracts&titles=Joseph_Black

**Comment by tomersmadja** [comment]
Thanks, I'll check it out

**Comment by martin-majlis** [comment]
There is however different API call - [parse](https://en.wikipedia.org/w/api.php?action=parse&page=List_of_masters_world_records_in_road_running) - that could be used and returns content as HTML with all the tags. Maybe this one could be used instead. :)
