### ISSUE TITLE
[Feature Request] API for wiki tables

### ISSUE THREAD

**Issue by skyprince999** [martin-majlis/Wikipedia-API#35]
Is it possible to create an API to extract tables from the wiki page?

**Comment by martin-majlis** [comment]
Wikipedia-API is using [extracts](https://www.mediawiki.org/wiki/Extension:TextExtracts#API) API call. For example this page - [List of masters world records in road running](https://en.wikipedia.org/wiki/List_of_masters_world_records_in_road_running) contains lot of tables. However when I try to load that page via [API](https://en.wikipedia.org/w/api.php?action=query&prop=extracts&titles=List_of_masters_world_records_in_road_running) - there are no tables returned.

**Comment by ScoobyQ** [comment]
Agreed. This is a highly popular action. Interesting will be the handling of frequently irregular shaped tables. I'm guessing something similar to pandas read_html handling?

**Comment by Guy-Markman** [comment]
Hi, because it hadn't been done by the original creator, I'm trying to do it myself. I'll do a push request if I'll succedd

**Comment by caniko** [comment]
Should probably use Pandas along with fletcher to store Python objects in the Dataframe efficiently.
