### ISSUE TITLE
section_by_title with identical names returns info from the last one only

### ISSUE THREAD

**Issue by Pancho-mk** [martin-majlis/Wikipedia-API#39]
section_by_title(title: str) 
In some pages with identical section names, like this one:
January in Events and January in Deaths in https://en.wikipedia.org/wiki/1920 
returns the info from Deaths only.
Is there a way to associate the content of that specific name January with the main section Events?

**Comment by martin-majlis** [comment]
@Pancho-mk : You can use `sections` attribute of the page to get all sections. Then you can recursively check, whether the subsection has title `Deaths`.

https://github.com/martin-majlis/Wikipedia-API/blob/master/API.rst#wikipediapagesection
