### ISSUE TITLE
Way to get plain Wikitext of page?

### ISSUE THREAD

**Issue by tomkcook** [martin-majlis/Wikipedia-API#4]
I'm feeling really dense... but once I've got a WikipediaPage, how do I get the wikitext for it?  I can only see ways of getting the text processed into plain text or HTML.

**Comment by martin-majlis** [comment]
If I understand this request correctly, you would like to receive an output in Wikipedia syntax?

**Comment by tomkcook** [comment]
Yes, that's right.
