### ISSUE TITLE
In-lined footnote references causes malformatted texts

### ISSUE THREAD

**Issue by johanbluecreek** [martin-majlis/Wikipedia-API#42]
If a paragraph (not a sentence nor word) ends with an in-lined footnote reference, the corresponding `.text` attribute will have a missing white-space there.

For example

```
wiki = wikipediaapi.Wikipedia('en')
page = wiki.page('Ross Ching')
for w in page.text.split():
    if '.' in w[:-1]:
        print(w)
```

prints

```
internet.A
outlets.Ching
bubbles.In
Jr.,
Wired.com,
Mashable.In
Wired.com
```

because `internet`, `outlets`, `bubbles`, `Mashable` are words at the end of a paragraph that has a footnote at the end.

Preferably, there would be a white-space after the `.` so that, for example, words could be extracted reliably from the text.

**Comment by KevinVanDyke** [comment]
I've just started using this library and ran into the same issue. Thought I'd comment to bring it to the attention of @martin-majlis and see if there is a workaround for this. This bug unfortunately makes the API rather unusable.

**Comment by martin-majlis** [comment]
Thanks for using this library.

When I check the API call, that is used for fetching `Ross Ching` - https://en.wikipedia.org/w/api.php?action=query&prop=extracts&titles=Ross%20Ching&explaintext=1&exsectionformat=wiki - I can see, that it's already there.

If you find in the documentation - https://www.mediawiki.org/w/api.php?action=help&modules=query%2Bextracts - how to get the correct text, I will fix it.

I am not sure, how to achieve that:
* wiki - https://en.wikipedia.org/w/api.php?action=query&prop=extracts&titles=Ross%20Ching&explaintext=1&exsectionformat=wiki
* plain - https://en.wikipedia.org/w/api.php?action=query&prop=extracts&titles=Ross%20Ching&explaintext=1&exsectionformat=plain
* raw - https://en.wikipedia.org/w/api.php?action=query&prop=extracts&titles=Ross%20Ching&explaintext=1&exsectionformat=wiki

**Comment by martin-majlis** [comment]
It was already reported as #46.
