### ISSUE TITLE
(sorry for such a dumb question but....)

### ISSUE THREAD

**Issue by elsrquetienelag** [martin-majlis/Wikipedia-API#49]
I'm new to this and I'm programming a voice assistant so I thought it would be good to put a wikipedia api since it looks extensive and with good reviews so I decided to try it but I don't know how to do it since I didn't understand well

![image](https://user-images.githubusercontent.com/109759426/180586110-a853e699-7ff3-45b6-94e4-77631dc1bdbc.png)
![image](https://user-images.githubusercontent.com/109759426/180586124-c3c8b767-eea6-41ed-a248-8ce40f890e7c.png)
I don't know what to do help :(

**Comment by n-st** [comment]
You've got a typo in your code: `sumary` should be `summary`.

**Comment by martin-majlis** [comment]
@elsrquetienelag : Thanks for using this package. There no dump questions. :) @n-st is right. There is typo in your code. If you use some better editor, it will help you with these problems. You can try https://code.visualstudio.com/

@n-st : Thanks for answering this question.
