### ISSUE TITLE
Incorrect response to a simple page() query

### ISSUE THREAD

**Issue by JBLarson** [martin-majlis/Wikipedia-API#50]
I noticed an issue where a wikipedia.page() search is returning the "Alboran Island"  page when I'm attempting to get the "Algorand" page. I've attached a screenshot demonstrating the issue.

I'm fairly certain the Algorand page should be retrievable with page("Algorand").
https://en.wikipedia.org/wiki/Algorand
Are there situations where the URL doesn't match the page name with the API?

![issue_8_7_wikipedia](https://user-images.githubusercontent.com/68449234/183289166-77ed8128-115f-4b6c-a9b7-7b6999880c64.png)

**Comment by JBLarson** [comment]
@martin-majlis

**Comment by aneziac** [comment]
This appears to be an issue with a different wikipedia API library: [wikipedia](https://pypi.org/project/wikipedia/) =/= [wikipedia-api](https://pypi.org/project/Wikipedia-API/).

**Comment by aneziac** [comment]
See [https://github.com/goldsmith/Wikipedia/issues/279](https://github.com/goldsmith/Wikipedia/issues/279)

**Comment by JBLarson** [comment]
thank you.
