### ISSUE TITLE
Print summary until end of paragraph

### ISSUE THREAD

**Issue by mrclean789** [martin-majlis/Wikipedia-API#51]
Is there a better way to get page summary so that it doesn't cut off? For e.g., start to end of first paragraph, or first two paragraphs.

**Comment by L1mak** [comment]
You will have to use nltk package (try tokenization function) or any other natural language processing library for it

**Comment by martin-majlis** [comment]
@mrclean789 : Do you have some example when this is happening?

Based on the API, there could be some limitation - https://www.mediawiki.org/w/api.php?action=help&modules=query%2Bextracts

**Comment by martin-majlis** [comment]
When I try the underlying API call - https://en.wikipedia.org/w/api.php?action=query&explaintext=1&exsectionformat=wiki&prop=extracts&titles=Planet& - it looks to me, that there is no restriction on the length of the response.
