### ISSUE TITLE
An unknown error occured: "Search request is longer than the maximum allowed length. (Actual: 655; allowed: 300)

### ISSUE THREAD

**Issue by TMachadoDev** [martin-majlis/Wikipedia-API#52]
Traceback (most recent call last):
  File "C:\Users\Aluno\Desktop\PowerPoints\main.py", line 26, in <module>
    ctg = wiki.page(pages).categories
  File "C:\Users\Aluno\AppData\Local\Programs\Python\Python310\lib\site-packages\wikipedia\wikipedia.py", line 270, in page
    results, suggestion = search(title, results=1, suggestion=True)
  File "C:\Users\Aluno\AppData\Local\Programs\Python\Python310\lib\site-packages\wikipedia\util.py", line 28, in __call__
    ret = self._cache[key] = self.fn(*args, **kwargs)
  File "C:\Users\Aluno\AppData\Local\Programs\Python\Python310\lib\site-packages\wikipedia\wikipedia.py", line 109, in search
    raise WikipediaException(raw_results['error']['info'])
wikipedia.exceptions.WikipediaException: An unknown error occured: "Search request is longer than the maximum allowed length. (Actual: 655; allowed: 300)". Please report it on GitHub!

**Comment by martin-majlis** [comment]
Could you, please, include some instructions how this could be reproduced?

**Comment by ShaneMellwig** [comment]
[]()SHANE Mellwig silver1fox1953@gmal.com s72613847@gmail.com s7153420@gmaol.com silver1fox1953@gmail.com Ishanemellwig > Traceback (most recent call last):
>   File "C:\Users\Aluno\Desktop\PowerPoints\main.py", line 26, in <module>
>     ctg = wiki.page(pages).categories
>   File "C:\Users\Aluno\AppData\Local\Programs\Python\Python310\lib\site-packages\wikipedia\wikipedia.py", line 270, in page
>     results, suggestion = search(title, results=1, suggestion=True)
>   File "C:\Users\Aluno\AppData\Local\Programs\Python\Python310\lib\site-packages\wikipedia\util.py", line 28, in __call__
>     ret = self._cache[key] = self.fn(*args, **kwargs)
>   File "C:\Users\Aluno\AppData\Local\Programs\Python\Python310\lib\site-packages\wikipedia\wikipedia.py", line 109, in search
>     raise WikipediaException(raw_results['error']['info'])
> wikipedia.exceptions.WikipediaException: An unknown error occured: "Search request is longer than the maximum allowed length. (Actual: 655; allowed: 300)". Please report it on GitHub!
>
