### ISSUE TITLE
page.sections is missing some sections

### ISSUE THREAD

**Issue by xenotropic** [martin-majlis/Wikipedia-API#61]
Somehow the third-level headings in this page get fetched but not the second-level headings? It has no first-level headings so maybe that throws it off. Or maybe I'm misunderstanding how sections is supposed to work. 

Code (using your example function):

```
import wikipediaapi
def print_sections(sections, level=0):
        for s in sections:
                print("%s: %s - %s" % ("*" * (level + 1), s.title, s.text[0:40]))
                print_sections(s.sections, level + 1)
             
wikipedia = wikipediaapi.Wikipedia('en')
page = wikipedia.page ( "Wikipedia:Spoken_articles")
print_sections ( page.sections )

```
Output, which is missing e.g., "Art, architecture and archaeology", "Biology" although it does show the level three headings under those "Art, architecture and archaeology biographies", "Biology biographies"

```
*: Art, architecture and archaeology biographies - 
**: Animals - 
**: Plants - 
**: Biology biographies - 
**: Business, economics, and finance biographies - 
**: Companies - 
**: Numismatics - 
**: Culture and society biographies - 
**: Human sexuality - 
**: Internet culture - 
**: Institutions - 
**: Africa - 
**: The Americas - 
***: The Caribbean and South America - 
***: North America - 
**: Asia - 
***: The Middle East - 
**: Europe - 
**: Oceania - 
**: Films - 
**: Television shows - 
**: Episodes of television - 
**: Media fictional characters - 
**: Media biographies - 
**: Albums - 
**: Songs - 
**: Music biographies - 
**: Political biographies - 
**: Sport and recreation biographies - 
Wikipedia:WikiProject Spoken Wikipedia/
```

**Comment by martin-majlis** [comment]
Links:
* page - https://en.wikipedia.org/wiki/Wikipedia:Spoken_articles
* api - https://en.wikipedia.org/w/api.php?action=query&prop=extracts&titles=Wikipedia:Spoken_articles&explaintext=1&exsectionformat=wiki

**Comment by martin-majlis** [comment]
Maybe the API call parse is better - https://www.mediawiki.org/w/api.php?action=help&modules=parse - https://en.wikipedia.org/w/api.php?action=parse&page=Wikipedia:Spoken_articles&prop=sections - that is returning more reasonable results
