### ISSUE TITLE
[Feature Request] Boolean denoting disambiguation page

### ISSUE THREAD

**Issue by HacMan137** [martin-majlis/Wikipedia-API#62]
It would be useful to be able to check whether the given page is a disambiguation page linking you to more specific pages. Right now disambiguation pages are treated as proper results when there should probably be a boolean denoting otherwise. Would allow programs trying to look up information about a specific topic an easy way to know it needs to spider the links and try to determine which pages are or are not relevant.

**Comment by martin-majlis** [comment]
Hi @HacMan137, do you have some example of such page?

**Comment by mohit-raghavendra** [comment]
Could this be such a page? - https://en.wikipedia.org/wiki/Python

**Comment by HacMan137** [comment]
@martin-majlis Sorry lost track of this. What @mohit-raghavendra shared is an example of what I'm talking about
