### ISSUE TITLE
Force users to respect Wikipedia's User Agent policy

### ISSUE THREAD

**Issue by XioNoX** [martin-majlis/Wikipedia-API#63]
(I'm a SRE at the Wikimedia Foundation)

We regularly get contacted by people getting rate limited while using the API, either directly or for example using your library.
Our API also gets occasionally and accidentally abused.

To help with those 2 issues, we require API users to define a non-default User-Agent, explained in this document: https://meta.wikimedia.org/wiki/User-Agent_policy

I'm wondering if it would be possible to add documentation in this regard to your library, as well as make the UA a mandatory configuration option.

**Comment by martin-majlis** [comment]
I have fixed in the PR #66. I will fix few more issues and I will release new version.

**Comment by martin-majlis** [comment]
I have released version 0.0.6 - https://pypi.org/project/Wikipedia-API/ - which makes the user agent mandatory. It's breaking change but hopefully people will understand it. :)
