### ISSUE TITLE
Summary method output not properly divided into paragraphs

### ISSUE THREAD

**Issue by Coderbeep** [martin-majlis/Wikipedia-API#76]
**Problem:**
When using the `summary` method of this library, the text output is not properly divided into paragraphs. The issue occurs specifically when the true paragraphs of the summary on the Wikipedia page end with citations (annotations).

**Steps to reproduce:**

1. Use the `wikipediaapi` library to retrieve the summary of the Wikipedia page.
2. Choose the Wikipedia page with annotations at the end of the paragraphs, such as [https://en.wikipedia.org/wiki/Nihilism](url)
3. Print the summary using the `summary` method (e.g. use code below)

**Expected behavior:**
The text output should accurately reflect the paragraph structure of the Wikipedia summary, with each paragraph separated appropriately.

**Actual behavior:**
If the real paragraph ends with annotations, the next one is concatenated to it, resulting in improper paragraphs structure.

``` python
import wikipediaapi
wiki_wiki = wikipediaapi.Wikipedia("example",'en')
    
page_py = wiki_wiki.page('Nihilism')
print(page_py.summary)
```

**Comment by Iriseve** [comment]
I have the same problem, is there any solution? @martin-majlis
