### ISSUE TITLE
Extractformat "HTML" doesnt include links

### ISSUE THREAD

**Issue by kittenswolf** [martin-majlis/Wikipedia-API#9]
The Extractformat "HTML" does not include links which can be found by visiting a wikipedia article in the browser.

**Comment by martin-majlis** [comment]
@kittenswolf : Do you have example where it does not work?

Please, reopen this issue if the problem is still there.

**Comment by laundmo** [comment]
this issue still happens

example code:

```py
import wikipediaapi
wiki_html =  wikipediaapi.Wikipedia(language='en', extract_format=wikipediaapi.ExtractFormat.HTML)
page_html = wiki_html.page("List_of_anime_distributed_in_the_United_States")
print(page_html.text)
```

this is the exact code that does not print `<a>` tags and is missing all the `href`s

please reopen, as i cant do so myself
